url: http://www.bluezd.info/
title: "Bluezd\'s Home"
description: Stay Focused ~ Stay Positive
#pygments: true
highlighter: true
theme: minima
#theme: jekyll-theme-architect
twitter_username: bluezd
github_username: bluezd
disqus:
        shortname: bluezd
