url: http://www.bluezd.info/
title: "Bluezd\'s Home"
description: Stay Focused ~ Stay Positive
#pygments: true
highlighter: true
theme: minima
#theme: jekyll-theme-architect
plugins: [jekyll-paginate]
paginate: 5
#paginate_path: "/posts:5/"
twitter_username: bluezhudong
github_username: bluezd
disqus:
        shortname: bluezd
